# Generated by Django 3.2.4 on 2022-12-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=64, verbose_name='Prezime')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Naziv')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naziv')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer', verbose_name='Proizvođač')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_power', models.IntegerField(blank=True, null=True, verbose_name='Konjska snaga')),
                ('capacity', models.CharField(max_length=3, verbose_name='Kubikaža')),
                ('year', models.IntegerField(verbose_name='Godina proizvodnje')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Detalji')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver', verbose_name='Driver')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model', verbose_name='Model')),
            ],
        ),
    ]
