# Generated by Django 3.2.4 on 2022-12-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
