# Generated by Django 3.2.4 on 2022-12-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221208_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='capacity',
        ),
        migrations.AddField(
            model_name='car',
            name='plates',
            field=models.CharField(max_length=20, null=True, verbose_name='Registracija'),
        ),
    ]
