# Generated by Django 4.1.3 on 2022-12-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221208_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Naslov')),
                ('news_category', models.CharField(max_length=64, verbose_name='Kategorija vijesti')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Datum objave')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ime autora')),
                ('surname', models.CharField(max_length=30, verbose_name='Prezime autora')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author', verbose_name='Author'),
        ),
    ]
