# Generated by Django 4.1.3 on 2022-12-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_author_date_of_birth_remove_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category'),
        ),
    ]
