# Generated by Django 4.1.3 on 2022-12-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.news', verbose_name='News'),
        ),
    ]
