# Generated by Django 4.1.3 on 2022-12-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_news_category_name_category_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='article',
        ),
    ]
