# Generated by Django 4.1.3 on 2022-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Broj telefona'),
        ),
    ]
