# Generated by Django 4.1.3 on 2022-12-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_author_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category'),
        ),
    ]
